### ISSUE TITLE
upload video can not play

### ISSUE THREAD

**Issue by SumatJiang** [dilab/resumable.php#3] opened 2015-11-05 03:33 UTC
Hi, i uploaded videos, the videos can not play

**Comment by dilab** [comment] 2015-11-09 06:41
Did it upload successfully if you check from the server side?

What format and size of the video file?

**Comment by dilab** [comment] 2015-12-20 03:38
Issue should be fixed with 0.1.2.

Issue was caused by `createFileFromChunks`, it does not combine chunks with correct order, applying `natsort` fixed the issue, thanks to @georaldc https://github.com/dilab/resumable.php/issues/2#issuecomment-164575724

**Closed as completed** 2015-12-20 03:41 UTC
Labels: bug
